# Generated by Django 3.2.9 on 2021-12-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='userman',
            new_name='user',
        ),
    ]
